<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerE5rYCRn\App_KernelProdContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerE5rYCRn/App_KernelProdContainer.php') {
    touch(__DIR__.'/ContainerE5rYCRn.legacy');

    return;
}

if (!\class_exists(App_KernelProdContainer::class, false)) {
    \class_alias(\ContainerE5rYCRn\App_KernelProdContainer::class, App_KernelProdContainer::class, false);
}

return new \ContainerE5rYCRn\App_KernelProdContainer([
    'container.build_hash' => 'E5rYCRn',
    'container.build_id' => '800a9ab7',
    'container.build_time' => 1666531290,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerE5rYCRn');
