<?php

namespace ContainerE5rYCRn;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getControllerServicesService extends App_KernelProdContainer
{
    /*
     * Gets the private 'App\Services\ControllerServices' shared autowired service.
     *
     * @return \App\Services\ControllerServices
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['App\\Services\\ControllerServices'] = new \App\Services\ControllerServices();
    }
}
