name: Symfony

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  unit-tests:
    runs-on: ubuntu-latest
    steps:
      #  To automatically get bug fixes and new Php versions for shivammathur/setup-php,
      # change this to (see https://github.com/shivammathur/setup-php#bookmark-versioning):
      # uses: shivammathur/setup-php@v2
      - uses: shivammathur/setup-php
        with:
          php-version: '8.1.11'
      - uses: actions/checkout@v3
      - name: Execute tests (Unit and Feature tests) via PHPUnit
        run: composer update && composer install && php bin/phpunit tests/Unit
